CREATE TABLE "allowlist" (
	"nr"	INTEGER NOT NULL UNIQUE,
	"path"	TEXT NOT NULL,
	PRIMARY KEY("nr" AUTOINCREMENT)
);

CREATE TABLE "denylist" (
	"nr"	INTEGER NOT NULL UNIQUE,
	"path"	TEXT NOT NULL,
	PRIMARY KEY("nr" AUTOINCREMENT)
);
